import React, { useEffect, useState } from "react";
import api from "../services/api";
import { BrainCircuit, CheckCircle, XCircle, AlertTriangle, Cpu } from "lucide-react";

export default function Models() {
  const [models, setModels] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    api.get("/models")
       .then(res => setModels(res.data))
       .catch(err => setError("Failed to load models."))
       .finally(() => setLoading(false));
  }, []);

  if (loading) return <div className="p-8 text-slate-400 font-mono animate-pulse">Loading model registry...</div>;
  if (error) return <div className="p-8 text-red-400 font-mono">Error: {error}</div>;

  return (
    <div className="p-8 max-w-7xl mx-auto">
      <header className="mb-8">
        <h2 className="text-3xl font-bold tracking-tight mb-2 flex items-center gap-3">
          <BrainCircuit className="text-blue-500" /> Detection Models
        </h2>
        <p className="text-slate-400 text-sm">Active machine learning classifiers and anomaly detection engines.</p>
      </header>
      
      <div className="bg-yellow-500/10 border border-yellow-500/20 rounded-xl p-6 mb-8 flex gap-4 text-yellow-500/90 shadow-lg">
        <AlertTriangle className="shrink-0 mt-1" size={24} />
        <div>
          <h4 className="font-bold text-lg mb-2 text-yellow-500">Evaluation Methodology Notice</h4>
          <p className="text-sm leading-relaxed text-yellow-500/80">
            The evaluation metrics below are strictly generated by evaluating the models against the unseen 30% fold of the <strong>synthetic demonstration dataset</strong>. Because the dataset relies on highly separable synthetic features (e.g., extremely high packet counts for volumetric flooding vs low counts for normal), the models naturally achieve extremely high theoretical accuracy (e.g., 1.0). These metrics prove the pipeline mathematical integrity, but do <strong>not</strong> represent real-world enterprise detection accuracy.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-8">
        {models.map(m => (
          <div key={m.name} className="bg-slate-900 border border-slate-800 rounded-xl shadow-xl overflow-hidden flex flex-col">
            <div className="p-6 border-b border-slate-800 bg-slate-900/50">
              <div className="flex justify-between items-start mb-1">
                <h3 className="text-xl font-bold text-slate-100">{m.name}</h3>
                {m.status === "LOADED" ? 
                  <span className="flex items-center gap-1.5 text-xs font-bold text-green-500 bg-green-500/10 px-2.5 py-1 rounded-md border border-green-500/20">
                    <CheckCircle size={14} /> LOADED
                  </span> : 
                  <span className="flex items-center gap-1.5 text-xs font-bold text-red-500 bg-red-500/10 px-2.5 py-1 rounded-md border border-red-500/20">
                    <XCircle size={14} /> OFFLINE
                  </span>
                }
              </div>
              <p className="text-sm text-blue-400 font-medium">{m.algorithm}</p>
            </div>
            
            <div className="p-6 flex-1 flex flex-col">
              <div className="grid grid-cols-2 gap-4 mb-8">
                <div className="bg-slate-950 p-4 rounded-lg border border-slate-800">
                  <div className="text-xs text-slate-500 font-semibold uppercase tracking-wider mb-1">Version</div>
                  <div className="font-mono text-slate-200">{m.version}</div>
                </div>
                <div className="bg-slate-950 p-4 rounded-lg border border-slate-800">
                  <div className="text-xs text-slate-500 font-semibold uppercase tracking-wider mb-1">Features</div>
                  <div className="font-mono text-slate-200">{m.features} Vector</div>
                </div>
              </div>

              {m.metrics && (
                <div className="mt-auto">
                  <h4 className="text-xs font-bold text-slate-600 mb-4 uppercase tracking-wider flex items-center gap-2">
                    <Cpu size={14} /> Evaluation Metrics (Test Set)
                  </h4>
                  <div className="grid grid-cols-2 gap-4">
                    {Object.entries(m.metrics).map(([k, v]) => (
                      <div key={k} className="flex justify-between items-end border-b border-slate-800/50 pb-2">
                        <span className="text-sm text-slate-400 capitalize">{k.replace('_', ' ')}</span>
                        <span className="text-lg font-mono font-bold text-slate-200">{String(v)}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
